name: Add a game or app
description: Request to add a new game or app to the site
title: 'Add: '
labels: ['Request']

body:
  - type: input
    attributes:
      label:
      placeholder: ''
    validations:
      required: true
  
      
  - type: input
    attributes:
      label: ⠀
      placeholder: ''
    validations:
      required: true
