name: add a game
description: Request to add a new game or app to the site
title: 'Add: '
labels: ['add game']

body:
  - type: input
    attributes:
      label: Name
      placeholder: 'Run 3'
    validations:
      required: true
  
      
  - type: input
    attributes:
      label: URL
      placeholder: 'https://mycoolsite.lol/ubg4/run3'
    validations:
      required: true
