name: Add a game or app
description: 
title: 'Add: '
labels: ['Request']

body:
  - type: input
    attributes:
      label: "Request"
      placeholder:
    validations:
      required: true
  
      
  - type: input
    attributes:
      label: "Request"
      placeholder:
    validations:
      required: true
