name: Sync Forks

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: sudo apt-get install -y git

      - name: Run Sync Script
        run: |
          mkdir -p /home/runner/work/clones
          export BASE_DIR="/home/runner/work/clones"
          python3 sync_forks.py
